name: Build and deploy Python app to Azure Web App - Pathly

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r backend/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3EB7002AA2E46F2B09087454DD8A7B7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C8E1614AB49A4C2D8CF1B9394FA7D0FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E541E94CB554E229D068EEFB563F8F2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Pathly'
          slot-name: 'Production'
          startup-command: 'cd /home/site/wwwroot && uvicorn main:app --host 0.0.0.0 --port 8000'
